# Using Numpy

In [1]:
## installing the library 
import numpy as np

#### NumPy Array
An array is a central data structure of the NumPy library. An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. It has a grid of elements that can be indexed in various ways.


In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Built-in Methods

There are lots of built-in ways to generate Arrays

### arange



In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones



In [8]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.ones((1,1))

array([[1.]])

### linspace


In [12]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [13]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

## Random 

### rand


In [14]:
np.random.rand(2)

array([0.24219532, 0.16410495])

In [15]:
np.random.rand(5,5)

array([[0.86031151, 0.89304822, 0.73741516, 0.34173472, 0.98039186],
       [0.25354165, 0.46684171, 0.95717764, 0.82051094, 0.79990743],
       [0.55243643, 0.59439128, 0.63177136, 0.76819459, 0.15701255],
       [0.88197313, 0.01772551, 0.97434675, 0.04163301, 0.63753481],
       [0.39310026, 0.59482412, 0.9293951 , 0.30780942, 0.65454521]])

### randn


In [16]:
np.random.randn(2)

array([ 1.32696709, -0.03483105])

In [17]:
np.random.randn(5,5)

array([[-0.79013321, -0.38517404, -0.43333316, -2.01251047, -0.65368048],
       [-0.26123079,  1.66846067,  0.38233631,  1.46118216, -1.00246038],
       [ 0.71652422,  0.17782008,  0.09878178,  0.92000973,  0.07278479],
       [ 0.79202688, -0.75675329,  1.58305665, -1.06672968,  1.63386034],
       [ 0.84375012, -1.32140089, -0.35487782, -1.1978663 ,  1.29248347]])

### Array Attributes and Methods


In [18]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [20]:
ranarr

array([ 2, 19, 22,  0, 23, 34, 41, 13, 25,  9])

### Reshape
Returns an array containing the same data with a new shape.

In [21]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max and min

In [22]:
ranarr.max()

41

In [23]:
ranarr.min()

0

### Shape and Reshape

Shape is an attribute that arrays have (not a method):

In [24]:
# Vector
arr.shape

(25,)

In [25]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [26]:
arr.reshape(1,25).shape

(1, 25)

In [27]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [28]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [29]:
arr.dtype

dtype('int64')

### Numpy Indexing and Selection
In this lecture we will discuss how to select elements or groups of elements from an array.

In [30]:
import numpy as np

In [31]:
#Creating sample array
arr = np.arange(0,11)

In [32]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Bracket Indexing and Selection


In [33]:
#Get a value at an index
arr[8]

8

In [34]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [35]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
#Data is not copied, it's a view of the original array! This avoids memory problems!

In [38]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [39]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [40]:
#Indexing row
arr_2d[1]


array([20, 25, 30])

In [41]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [42]:
# Getting individual element value
arr_2d[1,0]

20

In [43]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [44]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [45]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

### Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [46]:
arr = np.arange(1,4)
arr

array([1, 2, 3])

In [47]:
arr > 4

array([False, False, False])

In [48]:
bool_arr = arr>4

In [49]:
bool_arr

array([False, False, False])

In [50]:
arr[bool_arr]

array([], dtype=int64)

In [51]:
arr[arr>2]

array([3])

In [52]:
x = 2
arr[arr>x]

array([3])